# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.example: DEBUG
app:
  users-service:
    host: localhost
    port: 7001
  orders-service:
    host: localhost
    port: 7002
---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  users-service:
    host: users-service
    port: 8080
  orders-service:
    host: orders-service
    port: 8080
