# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.orders: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 0
      database: orders-db
      authentication-database: admin
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5
---
spring:
  config:
    activate:
      on-profile: docker

spring.data.mongodb.host: mongodb
spring.data.mongodb.port: 27017

server.port: 8080